# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

env:
  TAG_NAME: release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'
        dotnet-quality: 'ga'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish MisakaBiliApi/MisakaBiliApi.csproj -c Release -o Publish
    - run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: Publish/
        if-no-files-found: error
    - name: tar.gz Publish dir
      run: tar -czvf Publish.tar.gz Publish
    - name: Upload full firmware to release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: Publish.tar.gz
